<%
  branch = `git rev-parse --abbrev-ref HEAD`.strip rescue nil
  local_env = YAML.load_file("#{Rails.root}/local_env.yml").dig(Rails.env) || {}
%>

development:
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  database:  parti_home_development_<%= branch %>
  username:  <%= local_env.dig('database', 'username') %>
  password:  <%= local_env.dig('database', 'password') %>

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

test:
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  database:  parti_home_test_<%= branch %>
  username:  <%= local_env.dig('database', 'username') %>
  password:  <%= local_env.dig('database', 'password') %>
